use_frameworks!

target 'SwiftUtility_Example' do
  pod 'SwiftUtilityKit', :path => '../'

  target 'SwiftUtility_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
